apps/room/urls.py
from django.urls import path
from .views import RoomView, SingleRoomView

app_name = 'room'

urlpatterns = [
    path('room/', RoomView.as_view(), name='room'),
    path('single-room/<slug:slug>', SingleRoomView.as_view(), name='single-room')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contact/', include('apps.contact.urls', namespace='contact')),
    path('', include('apps.home.urls', namespace='home')),
    path('blog/', include('apps.blog.urls', namespace='blog')),
    path('room/', include('apps.room.urls', namespace='room'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/room/models.py
import time

from django.db import models
from django.utils.text import slugify


class Services(models.Model):
    name = models.CharField(max_length=225)
    image = models.ImageField(upload_to='media/rooms', blank=True, null=True)


class Room(models.Model):
    title = models.CharField(max_length=225)
    slug = models.SlugField(blank=True)
    cost = models.IntegerField(default=0)
    size = models.IntegerField()
    capacity = models.IntegerField()
    bed = models.CharField(max_length=225)
    image = models.ImageField(upload_to='media/rooms')
    description = models.TextField()
    adults = models.PositiveIntegerField(null=True, blank=True)
    children = models.PositiveIntegerField(null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            slug = slugify(str(self.title))
            timestamp = str(int(time.time()))
            self.slug = f"{slug}-{timestamp}"
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title


class RoomReview(models.Model):
    name = models.CharField(max_length=225)
    rating = models.IntegerField(default=0)
    description = models.TextField()
    room = models.ManyToManyField(Room)
    image = models.ImageField(upload_to='media/rooms', blank=True, null=True)
    created_date = models.DateTimeField(auto_now_add=True)


class Booking(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='datas', blank=True, null=True)
    check_in = models.DateField()
    check_out = models.DateField()
    adults = models.PositiveIntegerField()
    children = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.room.title} - Check-in: {self.check_in}, Check-out: {self.check_out}, Adults: {self.adults}, Children: {self.children}"

    @staticmethod
    def is_room_booked(room_id, check_date):
        bookings_on_date = Booking.objects.filter(room_id=room_id, check_in__lte=check_date, check_out__gt=check_date)
        return bookings_on_date.exists()

apps/room/forms.py
from django import forms

from .models import Booking


class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ['room', 'check_in', 'check_out', 'adults', 'children']

    # room = forms.ChoiceField(
    #     choices=[('00', '00'), ('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06')],
    #     widget=forms.Select(attrs={'class': 'form-control'}))
    #
    # adults = forms.ChoiceField(
    #     choices=[('00', '00'), ('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06')],
    #     widget=forms.Select(attrs={'class': 'form-control'}))
    #
    # children = forms.ChoiceField(
    #     choices=[('00', '00'), ('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06')],
    #     widget=forms.Select(attrs={'class': 'form-control'}))
    #
    # check_in = forms.DateField(
    #     widget=forms.DateInput(attrs={'class': 'form-control', 'id': 'checkIn', 'name': 'checkin-date'}))
    #
    # check_out = forms.DateField(
    #     widget=forms.DateInput(attrs={'class': 'form-control', 'id': 'checkIn', 'name': 'checkin-date'}))
    #
    # def __init__(self, *args, **kwargs):
    #     super(BookingForm, self).__init__(*args, **kwargs)
    #     self.fields['room'].widget.attrs.update({
    #         'class': 'form-control',
    #         'name': 'room',
    #         'id': 'room',
    #     })
    #     self.fields['check_in'].widget.attrs.update({
    #         'class': 'form-control',
    #         'id': 'checkIn',
    #         'name': 'check_in',
    #         'type': 'data'
    #     })
    #     self.fields['check_out'].widget.attrs.update({
    #         'class': 'form-control',
    #         'id': 'checkOut',
    #         'name': 'check_out',
    #         'type': 'data'
    #     })
    #     self.fields['adults'].widget.attrs.update({
    #         'class': 'form-control',
    #         'id': 'adults',
    #         'name': 'adults'
    #     })
    #     self.fields['children'].widget.attrs.update({
    #         'class': 'form-control',
    #         'id': 'children',
    #         'name': 'adults'
    #     })

apps/room/views.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import DetailView, ListView
from django.views.generic.edit import FormMixin
from django.shortcuts import get_object_or_404

from apps.home.models import Feedback
from .forms import BookingForm
from .models import Room, Services, RoomReview, Booking


class RoomView(ListView):
    model = Room
    template_name = 'room/room.html'
    context_object_name = 'rooms'

    def get_context_data(self, **kwargs):
        context = super(RoomView, self).get_context_data(**kwargs)
        context['booking_form'] = BookingForm()
        return context

    def get(self, request, *args, **kwargs):
        rooms = Room.objects.order_by('-id')
        check_in = request.GET.get('check_in')
        check_out = request.GET.get('check_out')
        adults = request.GET.get('adults')
        children = request.GET.get('children')
        if check_in or check_out:
            rooms = rooms.filter(~Q(datas__check_in__lte=check_out) |~Q(datas__check_out__gte=check_in))
        if adults or children:
            children = int(children)
            adults = int(adults)
            rooms = rooms.filter(Q(children__gte=children) or Q(adults__gte=adults))

        paginator = Paginator(rooms, 5)
        page = request.GET.get('p')
        rooms = paginator.get_page(page)

        context = {
            'rooms': rooms,
        }
        return render(request, self.template_name, context)


class SingleRoomView(FormMixin, DetailView):
    model = Room
    template_name = 'room/single-room.html'
    context_object_name = 'room'
    form_class = BookingForm

    def get_success_url(self):
        return self.request.path

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        room_slug = self.kwargs.get('slug')
        check_in = form.cleaned_data['check_in']
        check_out = form.cleaned_data['check_out']
        adults = form.cleaned_data['adults']
        children = form.cleaned_data['children']
        print(room_slug)
        try:
            room = Room.objects.get(slug=room_slug)
        except Room.DoesNotExist:
            messages.error(self.request, 'The specified room does not exist.')
            return self.form_invalid(form)

        if check_in and check_out:
            Booking.objects.create(
                room=room,
                check_in=check_in,
                check_out=check_out,
                adults=adults,
                children=children
            )
            messages.success(self.request, 'The room has been successfully booked!')
            return redirect(self.get_success_url())

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rooms_images'] = Room.objects.order_by('-id')[:5]
        context['services'] = Services.objects.order_by('-id')[:6]
        context['reviews'] = RoomReview.objects.order_by('-id')[:3]
        context['date_format'] = "M d, Y"
        context['form'] = self.get_form()
        return context

templates/room/room.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="breadcrumb-area bg-img bg-overlay jarallax"
         style="background-image: url({% static 'img/bg-img/16.jpg' %});">
        <div class="container h-100">
            <div class="row h-100 align-items-center">
                <div class="col-12">
                    <div class="breadcrumb-content text-center">
                        <h2 class="page-title">Our Room</h2>
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb justify-content-center">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Room</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="roberto-rooms-area section-padding-100-0">
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-8">
                    {% for room in rooms %}
                        <div class="single-room-area d-flex align-items-center mb-50 wow fadeInUp"
                             data-wow-delay="100ms">

                            <div class="room-thumbnail">
                                <img src="{{ room.image.url }}" alt>
                            </div>

                            <div class="room-content">
                                <h2>{{ room.title }}</h2>
                                <h4>{{ room.cost }}$ <span>/ Day</span></h4>
                                <div class="room-feature">
                                    <h6>Size: <span>{{ room.size }} ft</span></h6>
                                    <h6>Capacity: <span>Max person {{ room.capacity }}</span></h6>
                                    <h6>Bed: <span>{{ room.bed }}</span></h6>
                                    <h6>Services: <span>Wifi, television ...</span></h6>
                                </div>
                                <a href="{% url 'room:single-room' room.slug %}" class="btn view-detail-btn">View Details <i class="fa fa-long-arrow-right" aria-hidden="true"></i></a>
                            </div>
                        </div>
                    {% endfor %}


                    <nav class="roberto-pagination wow fadeInUp mb-100" data-wow-delay="1000ms">
                        <ul class="pagination">
                            {% if rooms.has_previous %}
                                <span class="page-item"><a class="page-link"
                                                           href="?p={{ rooms.previous_page_number }}">&laquo;</a></span>
                            {% else %}
                                <span class="page-item disabled"><span class="page-link">&laquo;</span></span>
                            {% endif %}
                            {% for i in rooms.paginator.page_range %}
                                {% if rooms.number == i %}
                                    <span class="page-item active"><span class="page-link">{{ i }}<span
                                            class="sr-only"></span></span></span>
                                {% else %}
                                    <span class="page-item"><a class="page-link" href="?p={{ i }}">{{ i }}</a></span>
                                {% endif %}
                            {% endfor %}
                            {% if rooms.has_next %}
                                <span class="page-item"><a class="page-link" href="?p={{ rooms.next_page_number }}">&raquo;</a></span>
                            {% else %}
                                <span class="page-item disabled"><span class="page-link">&raquo;</span></span>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
                <div class="col-12 col-lg-4">

                    <div class="hotel-reservation--area mb-100">
                        <form method="get">
                            <div class="form-group mb-30">
                                <label for="checkInDate">Date</label>
                                <div class="" id="datepicker">
                                    <div class="row no-gutters">
                                        <div class="col-6">
                                            <input type="date" class="input-small form-control" id="checkInDate"
                                                   name="check_in" placeholder="Check In">
                                        </div>
                                        <div class="col-6">
                                            <input type="date" class="input-small form-control" name="check_out"
                                                   placeholder="Check Out">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group mb-30">
                                <label for="guests">Guests</label>
                                <div class="row">
                                    <div class="col-6">
                                        <select name="adults" id="guests" class="form-control">
                                            <option value="0">Adults</option>
                                            <option value="1">01</option>
                                            <option value="2">02</option>
                                            <option value="3">03</option>
                                            <option value="4">04</option>
                                            <option value="5">05</option>
                                            <option value="6">06</option>
                                        </select>
                                    </div>
                                    <div class="col-6">
                                        <select name="children" id="children" class="form-control">
                                            <option value="0">Children</option>
                                            <option value="1">01</option>
                                            <option value="2">02</option>
                                            <option value="3">03</option>
                                            <option value="4">04</option>
                                            <option value="5">05</option>
                                            <option value="6">06</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
{#                            <div class="form-group mb-50">#}
{#                                <div class="slider-range">#}
{#                                    <div class="range-price">Max Price: $0 - $3000</div>#}
{#                                    <div data-min="0" data-max="3000" data-unit="$"#}
{#                                         class="slider-range-price ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all"#}
{#                                         data-value-min="0" data-value-max="3000" data-label-result="Max Price: ">#}
{#                                        <div class="ui-slider-range ui-widget-header ui-corner-all"></div>#}
{#                                        <span class="ui-slider-handle ui-state-default ui-corner-all"#}
{#                                              tabindex="0"></span>#}
{#                                        <span class="ui-slider-handle ui-state-default ui-corner-all"#}
{#                                              tabindex="0"></span>#}
{#                                    </div>#}
{#                                </div>#}
{#                            </div>#}
                            <div class="form-group">
                                <button type="submit" class="btn roberto-btn w-100">Check Available</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/room/single-room.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    
    {% if messages %}
        <ul>
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    
    <div class="breadcrumb-area bg-img bg-overlay jarallax"
         style="background-image: url({% static 'img/bg-img/16.jpg' %});">
        <div class="container h-100">
            <div class="row h-100 align-items-end">
                <div class="col-12">
                    <div class="breadcrumb-content d-flex align-items-center justify-content-between pb-5">
                        <h2 class="room-title">{{ room.title }}</h2>
                        <h2 class="room-price">${{ room.cost }} <span>/ Per Night</span></h2>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="roberto-rooms-area section-padding-100-0">
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-8">

                    <div class="single-room-details-area mb-50">

                        <div class="room-thumbnail-slides mb-50">
                            <div id="room-thumbnail--slide" class="carousel slide" data-ride="carousel">
                                <div class="carousel-inner">
                                    <div class="carousel-item active">
                                        <img src="{% static 'img/bg-img/48.jpg' %}" class="d-block w-100" alt>
                                    </div>
                                    <div class="carousel-item">
                                        <img src="{% static 'img/bg-img/49.jpg' %}" class="d-block w-100" alt>
                                    </div>
                                    <div class="carousel-item">
                                        <img src="{% static 'img/bg-img/50.jpg' %}" class="d-block w-100" alt>
                                    </div>
                                    <div class="carousel-item">
                                        <img src="{% static 'img/bg-img/51.jpg' %}" class="d-block w-100" alt>
                                    </div>
                                    <div class="carousel-item">
                                        <img src="{% static 'img/bg-img/52.jpg' %}" class="d-block w-100" alt>
                                    </div>
                                </div>
                                <ol class="carousel-indicators">
                                    <li data-target="#room-thumbnail--slide" data-slide-to="0" class="active">
                                        <img src="{% static 'img/bg-img/48.jpg' %}" class="d-block w-100" alt>
                                    </li>
                                    <li data-target="#room-thumbnail--slide" data-slide-to="1">
                                        <img src="{% static 'img/bg-img/49.jpg' %}" class="d-block w-100" alt>
                                    </li>
                                    <li data-target="#room-thumbnail--slide" data-slide-to="2">
                                        <img src="{% static 'img/bg-img/50.jpg' %}" class="d-block w-100" alt>
                                    </li>
                                    <li data-target="#room-thumbnail--slide" data-slide-to="3">
                                        <img src="{% static 'img/bg-img/51.jpg' %}" class="d-block w-100" alt>
                                    </li>
                                    <li data-target="#room-thumbnail--slide" data-slide-to="4">
                                        <img src="{% static 'img/bg-img/52.jpg' %}" class="d-block w-100" alt>
                                    </li>
                                </ol>
                            </div>
                        </div>

                        <div class="room-features-area d-flex flex-wrap mb-50">
                            <h6>Size: <span>{{ room.size }}ft</span></h6>
                            <h6>Capacity: <span>Max person {{ room.capacity }}</span></h6>
                            <h6>Bed: <span>{{ room.bed }}</span></h6>
                            <h6>Services: <span>Wifi, television ...</span></h6>
                        </div>
                        <p>{{ room.description }}</p>
                    </div>

                    <div class="room-service mb-50">
                        <h4>Room Services</h4>
                        <ul>
                            {% for service in services %}
                                <li><img src="{{ service.image.url }}" alt> {{ service.name }}</li>
                            {% endfor %}
                        </ul>
                    </div>

                    <div class="room-review-area mb-100">
                        <h4>Room Review</h4>
                        {% for foo in reviews %}
                            <div class="single-room-review-area d-flex align-items-center">
                                {% if foo.image %}
                                    <div class="reviwer-thumbnail">
                                        <img src="{{ foo.image.url }}" alt>
                                    </div>
                                {% endif %}
                                <div class="reviwer-content">
                                    <div class="reviwer-title-rating d-flex align-items-center justify-content-between">
                                        <div class="reviwer-title">
                                            <span>{{ foo.created|date:date_format }}</span>
                                            <h6>Brandon Kelley</h6>
                                        </div>
                                        <div class="reviwer-rating">
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                        </div>
                                    </div>
                                    <p>{{ foo.description }}</p>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            
                <div class="col-12 col-lg-4">
                    <div class="hotel-reservation--area mb-100">
                        <form method="post">
                            {% csrf_token %}
                            <div class="form-group mb-30">
                                <label for="checkInDate">Date</label>
                                <div class="input-daterange" id="datepicker">
                                    <div class="row no-gutters">
                                        <div class="col-6">
                                            <input type="date" class="input-small form-control" name="check_in" placeholder="Check In">
                                        </div>
                                        <div class="col-6">
                                            <input type="date" class="input-small form-control" name="check_out"
                                                   placeholder="Check Out">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group mb-30">
                                <label for="guests">Guests</label>
                                <div class="row">
                                    <div class="col-6">
                                        <select name="adults" id="guests" class="form-control">
                                            <option value="0">Adults</option>
                                            <option value="1">01</option>
                                            <option value="2">02</option>
                                            <option value="3">03</option>
                                            <option value="4">04</option>
                                            <option value="5">05</option>
                                            <option value="6">06</option>
                                        </select>
                                    </div>
                                    <div class="col-6">
                                        <select name="children" id="children" class="form-control">
                                            <option value="0">Children</option>
                                            <option value="1">01</option>
                                            <option value="2">02</option>
                                            <option value="3">03</option>
                                            <option value="4">04</option>
                                            <option value="5">05</option>
                                            <option value="6">06</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn roberto-btn w-100">Check Available</button>
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock %}