apps/blog/urls.py
from django.urls import path
from .views import BlogView, BlogDetailView #BlogSingle, CommentCreateView

app_name = 'blog'

urlpatterns = [
    path('blog/', BlogView.as_view(), name='blog'),
    path('single_blog/<slug:slug>', BlogDetailView.as_view(), name='single-blog'),
]

apps/contact/urls.py
from django.urls import path
from .views import ContactView

app_name = 'contact'

urlpatterns = [
    path('contact/', ContactView.as_view(), name='contact')
]

apps/home/urls.py
from django.urls import path

from .views import HomeView, AboutView

app_name = 'home'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about')
]

apps/room/urls.py
from django.urls import path
from .views import RoomView, SingleRoomView

app_name = 'room'

urlpatterns = [
    path('room/', RoomView.as_view(), name='room'),
    path('single-room/<slug:slug>', SingleRoomView.as_view(), name='single-room')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contact/', include('apps.contact.urls', namespace='contact')),
    path('', include('apps.home.urls', namespace='home')),
    path('blog/', include('apps.blog.urls', namespace='blog')),
    path('room/', include('apps.room.urls', namespace='room'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<!-- Mirrored from preview.colorlib.com/theme/roberto/ by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 11 Feb 2024 10:32:10 GMT -->
<head>
    <meta charset="UTF-8">
    <meta name="description" content>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Roberto - Hotel &amp; Resort HTML Template</title>

    <link rel="icon" href="{% static 'img/core-img/favicon.png' %}">

    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script nonce="df778ee7-1f19-4c46-9402-49bc39676907">try {
        (function (w, d) {
            !function (o, p, q, r) {
                o[q] = o[q] || {};
                o[q].executed = [];
                o.zaraz = {deferred: [], listeners: []};
                o.zaraz.q = [];
                o.zaraz._f = function (s) {
                    return async function () {
                        var t = Array.prototype.slice.call(arguments);
                        o.zaraz.q.push({m: s, a: t})
                    }
                };
                for (const u of ["track", "set", "debug"]) o.zaraz[u] = o.zaraz._f(u);
                o.zaraz.init = () => {
                    var v = p.getElementsByTagName(r)[0], w = p.createElement(r),
                        x = p.getElementsByTagName("title")[0];
                    x && (o[q].t = p.getElementsByTagName("title")[0].text);
                    o[q].x = Math.random();
                    o[q].w = o.screen.width;
                    o[q].h = o.screen.height;
                    o[q].j = o.innerHeight;
                    o[q].e = o.innerWidth;
                    o[q].l = o.location.href;
                    o[q].r = p.referrer;
                    o[q].k = o.screen.colorDepth;
                    o[q].n = p.characterSet;
                    o[q].o = (new Date).getTimezoneOffset();
                    if (o.dataLayer) for (const B of Object.entries(Object.entries(dataLayer).reduce(((C, D) => ({...C[1], ...D[1]})), {}))) zaraz.set(B[0], B[1], {scope: "page"});
                    o[q].q = [];
                    for (; o.zaraz.q.length;) {
                        const E = o.zaraz.q.shift();
                        o[q].q.push(E)
                    }
                    w.defer = !0;
                    for (const F of [localStorage, sessionStorage]) Object.keys(F || {}).filter((H => H.startsWith("_zaraz_"))).forEach((G => {
                        try {
                            o[q]["z_" + G.slice(7)] = JSON.parse(F.getItem(G))
                        } catch {
                            o[q]["z_" + G.slice(7)] = F.getItem(G)
                        }
                    }));
                    w.referrerPolicy = "origin";
                    w.src = "https://preview.colorlib.com/cdn-cgi/zaraz/s.js?z=" + btoa(encodeURIComponent(JSON.stringify(o[q])));
                    v.parentNode.insertBefore(w, v)
                };
                ["complete", "interactive"].includes(p.readyState) ? zaraz.init() : o.addEventListener("DOMContentLoaded", zaraz.init)
            }(w, d, "zarazData", "script");
        })(window, document)
    } catch (e) {
        throw fetch("/cdn-cgi/zaraz/t"), e;
    }
    </script>
</head>
<body>

<div id="preloader">
    <div class="loader"></div>
</div>

{% include 'header.html' %}

{% block content %}

{% endblock %}

<section class="roberto-cta-area">
    <div class="container">
        <div class="cta-content bg-img bg-overlay jarallax" style="background-image: url({% static 'img/bg-img/1.jpg' %});">
            <div class="row align-items-center">
                <div class="col-12 col-md-7">
                    <div class="cta-text mb-50">
                        <h2>Contact us now!</h2>
                        <h6>Contact (+12) 345-678-9999 to book directly or for advice</h6>
                    </div>
                </div>
                <div class="col-12 col-md-5 text-right">
                    <a href="#" class="btn roberto-btn mb-50">Contact Now</a>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="partner-area">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="partner-logo-content d-flex align-items-center justify-content-between wow fadeInUp" data-wow-delay="300ms">
                    {% for partner in partnersData %}
                        <a href="#" class="partner-logo"><img src="{{ partner.image.url }}" alt></a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

{% include 'footer.html' %}

<script src="{% static 'js/jquery.min.js' %}"></script>

<script src="{% static 'js/popper.min.js' %}"></script>

<script src="{% static 'js/bootstrap.min.js' %}"></script>

<script src="{% static 'js/roberto.bundle.js' %}"></script>

<script src="{% static 'js/default-assets/active.js' %}"></script>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
        dataLayer.push(arguments);
    }

    gtag('js', new Date());

    gtag('config', 'UA-23581568-13');
</script>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/v84a3a4012de94ce1a686ba8c167c359c1696973893317"
        integrity="sha512-euoFGowhlaLqXsPWQ48qSkBSCFs3DPRyiwVu3FjR96cMPx+Fr+gpWRhIafcHwqwCqWS42RZhIudOvEI+Ckf6MA=="
        data-cf-beacon='{"rayId":"853bed269da60506","b":1,"version":"2024.2.0","token":"cd0b4b3a733644fc843ef0b185f98241"}'
        crossorigin="anonymous"></script>
</body>

<!-- Mirrored from preview.colorlib.com/theme/roberto/ by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 11 Feb 2024 10:32:56 GMT -->
</html>

templates/footer.html
{% load static %}
<footer class="footer-area section-padding-80-0">

    <div class="main-footer-area">
        <div class="container">
            <div class="row align-items-baseline justify-content-between">

                <div class="col-12 col-sm-6 col-lg-3">
                    <div class="single-footer-widget mb-80">

                        <a href="#" class="footer-logo"><img src="{% static 'img/core-img/logo2.png' %}" alt></a>
                        <h4>+12 345-678-9999</h4>
                        <span><a href="https://preview.colorlib.com/cdn-cgi/l/email-protection" class="__cf_email__"
                                 data-cfemail="2960474f46074a4645465b45404b694e44484045074a4644">[email&#160;protected]</a></span>
                        <span>856 Cordia Extension Apt. 356, Lake Deangeloburgh, South Africa</span>
                    </div>
                </div>

                <div class="col-12 col-sm-6 col-lg-3">
                    <div class="single-footer-widget mb-80">

                        <h5 class="widget-title">Our Blog</h5>

                        <div class="latest-blog-area">
                            <a href="#" class="post-title">Freelance Design Tricks How</a>
                            <span class="post-date"><i class="fa fa-clock-o" aria-hidden="true"></i> Jan 02, 2019</span>
                        </div>

                        <div class="latest-blog-area">
                            <a href="#" class="post-title">Free Advertising For Your Online</a>
                            <span class="post-date"><i class="fa fa-clock-o" aria-hidden="true"></i> Jan 02, 2019</span>
                        </div>
                    </div>
                </div>

                <div class="col-12 col-sm-4 col-lg-2">
                    <div class="single-footer-widget mb-80">

                        <h5 class="widget-title">Links</h5>

                        <ul class="footer-nav">
                            <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i> About Us</a></li>
                            <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i> Our Room</a></li>
                            <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i> Career</a></li>
                            <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i> FAQs</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-12 col-sm-8 col-lg-4">
                    <div class="single-footer-widget mb-80">

                        <h5 class="widget-title">Subscribe Newsletter</h5>
                        <span>Subscribe our newsletter gor get notification about new updates.</span>

                        <form action="https://preview.colorlib.com/theme/roberto/index.html" class="nl-form">
                            <input type="email" class="form-control" placeholder="Enter your email...">
                            <button type="submit"><i class="fa fa-paper-plane" aria-hidden="true"></i></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="copywrite-content">
            <div class="row align-items-center">
                <div class="col-12 col-md-8">

                    <div class="copywrite-text">
                        <p>
                            Copyright &copy;<script data-cfasync="false"
                                                    src="https://preview.colorlib.com/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
                            <script>document.write(new Date().getFullYear());</script>
                            All rights reserved | This template is made with <i class="fa fa-heart-o"
                                                                                aria-hidden="true"></i> by <a
                                href="https://colorlib.com/" target="_blank">Colorlib</a>
                        </p>
                    </div>
                </div>
                <div class="col-12 col-md-4">

                    <div class="social-info">
                        <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                        <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                        <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                        <a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/header.html
{% load static %}
<header class="header-area">
{#    <div class="search-form d-flex align-items-center">#}
{#        <div class="container">#}
{#            <form action="https://preview.colorlib.com/theme/roberto/index.html" method="get">#}
{#                <input type="search" name="search-form-input" id="searchFormInput" placeholder="Type your keyword ...">#}
{#                <button type="submit"><i class="icon_search"></i></button>#}
{#            </form>#}
{#        </div>#}
{#    </div>#}

    <div class="top-header-area">
        <div class="container">
            <div class="row">
                <div class="col-6">
                    <div class="top-header-content">
                        <a href="#"><i class="icon_phone"></i> <span>(123) 456-789-1230</span></a>
                        <a href="#"><i class="icon_mail"></i> <span><span class="__cf_email__"
                                                                          data-cfemail="e78e898188c984888b88958b8e85a7808a868e8bc984888a">[email&#160;protected]</span></span></a>
                    </div>
                </div>
                <div class="col-6">
                    <div class="top-header-content">

                        <div class="top-social-area ml-auto">
                            <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                            <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                            <a href="#"><i class="fa fa-tripadvisor" aria-hidden="true"></i></a>
                            <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="main-header-area">
        <div class="classy-nav-container breakpoint-off">
            <div class="container">

                <nav class="classy-navbar justify-content-between" id="robertoNav">

                    <a class="nav-brand" href="#"><img src="{% static 'img/core-img/logo.png' %}" alt></a>

                    <div class="classy-navbar-toggler">
                        <span class="navbarToggler"><span></span><span></span><span></span></span>
                    </div>

                    <div class="classy-menu">

                        <div class="classycloseIcon">
                            <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                        </div>

                        <div class="classynav">
                            <ul id="nav">
                                <li class="active"><a href="{% url 'home:home' %}">Home</a></li>
                                <li><a href="{% url 'room:room' %}">Rooms</a></li>
                                <li><a href="{% url 'home:about' %}">About Us</a></li>
                                <li><a href="{% url 'blog:blog' %}">News</a></li>
                                <li><a href="{% url 'contact:contact' %}">Contact</a></li>
                            </ul>

                            <div class="search-btn ml-4">
                                <i class="fa fa-search" aria-hidden="true"></i>
                            </div>

                            <div class="book-now-btn ml-3 ml-lg-5">
                                <a href="#">Book Now <i class="fa fa-long-arrow-right" aria-hidden="true"></i></a>
                            </div>
                        </div>

                    </div>
                </nav>
            </div>
        </div>
    </div>
</header>